### ISSUE TITLE
Where is v0.0.8 ?

### ISSUE THREAD

**Issue by addshore** [survivorbat/gorm-deep-filtering#2]
Hi @survivorbat 

I just started using this package and was going to provide a PR improvement for some many2many relation stuff.
However I appear to be using v0.0.8 but I can't actually find that tag / the code in this repo?
Can you offer some help? :)

**Comment by survivorbat** [comment]
Hey @addshore! Thanks for showing interest in the development. I was actually quite stumped when I read your issue because I forgot where v0.0.8 came from as well. 

v0.0.8 and all the versions in between were draft/pre-release versions that incorporated the feature that is now gorm-like but were later abandoned in favor of a separate plugin. It appears my own projects are also using this ghost version. I don't recall why I turned them into tags, rather than just using the git hashes.

I suppose this would be rectified with a new tag on master like v0.0.9, although I'd prefer (finally) releasing v1.0.0 to justify a breaking change removing this abandoned code.

Hope that clears up the confusion, the intended state of the library should be the master branch. I'll delete the 2 branches with this unfinished code asap :)

**Comment by addshore** [comment]
Hehe, nothing like coming back to a project after a year.

The patch I wrote is https://github.com/addshore/gorm-deep-filtering/commit/1f34f64d390d22ad6cdd692054a6dc63be4f1397 and is actually for the functionality on the `feature/improve-like` branch
But it sounds like you might be getting rid of that functionality? (personally I quite like it ;))

**Comment by survivorbat** [comment]
This one is much more functional than whatever is in there: [gorm-like](https://github.com/survivorbat/gorm-like)

**Comment by addshore** [comment]
Lovely, I'll take a look and try to transfer over :)
Might be worth noting that one in the README too :)

**Comment by addshore** [comment]
well, that was easy...

```
-       deepgorm "github.com/survivorbat/gorm-deep-filtering"
+       gormlike "github.com/survivorbat/gorm-like"


-       DB.Use(deepgorm.New(deepgorm.Wildcards()))
+       DB.Use(gormlike.New(gormlike.WithCharacter("*")))
```

No other changes needed

**Comment by survivorbat** [comment]
I do intend to remove the functionality from deepgorm, gormlike should be enough. But that would be v1.0.0 ;)

**Comment by survivorbat** [comment]
Hey @addshore! A bit unrelated, but will you merge your improvements to master? I think it'd make a great addition

**Comment by addshore** [comment]
https://github.com/survivorbat/gorm-deep-filtering/pull/3
